apiVersion: capabilities-gen
kind: Deployment
metadata:
  name: capabilities-gen
spec:
  selector:
    matchLabels:
      app: capabilities-gen
  replicas: 1
  template:
    metadata:
      labels:
        app: capabilities-gen
    spec:
      volumes:
        - name: model-volume
          emptyDir: {}
      initContainers:
        - name: model-init
          image: pdok/ogc-capabilities-gen:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "cp /config/* /config"]
          volumeMounts:
            - name: model-volume
              mountPath: "/config"
      containers:
        - name: capabilities-gen
          image: pdok/ogc-capabilities-gen:latest
          imagePullPolicy: Always
          command: ["-e SERVICE_TYPE=wms -e SERVICE_VERSION=1.3.0 -e SERVICE_CONFIG_PATH=/config/input.yaml"]
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 25
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 25
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          ports:
            - name: capabilities-gen
              containerPort: 8000
          volumeMounts:
            - name: model-volume
              mountPath: /config