global:
  prefix: bo
  namespace: http://www.BlueOx.org/BlueOx
  onlineresourceurl: http://www.BlueOx.org
  path: /wfs/wfs.cgi
services:
  wfs200:
    filename: ./output/wfs_capabilities_2_0_0.xml
    definition:
      serviceIdentification:
        title: OGC Member WFS
        abstract: "Web Feature Service maintained by NSDI data provider, serving FGDC framework layer XXX; contact Paul.Bunyon@BlueOx.org"
        keywords:
          keyword:
            - Kadaster
            - Kadastrale percelen
            - FGDC
            - NSDI
            - Framework Data Layer
            - BlueOx
          type:
            text: string
        fees: NONE
        accessConstraints: NONE
      serviceProvider:
        providerName: BlueOx Inc.
        providerSite:
          type: simple
          href: http://www.cubewerx.com
        serviceContact:
          individualName: Paul Bunyon
          positionName: Mythology Manager
          contactInfo:
            phone:
              voice: 1.800.BIG.WOOD
              facsimile: 1.800.FAX.WOOD
            address:
              deliveryPoint: North Country
              city: Small Town
              administrativeArea: Rural County
              postalCode: 12345
              country: USA
              electronicMailAddress: Paul.Bunyon@BlueOx.org
            onlineResource:
              type: simple
              href: http://www.BlueOx.org/contactUs
            hoursOfService: 24x7
            contactInstructions: eMail Paul with normal requsts; Phone Paul for emergency
               requests; if you get voice mail and your request can't wait,
               contact another mythological figure listed on the contactUs
               page of our web site.
          role: PointOfContact
      capabilities:
        operationsMetadata:
          operation:
            - name: GetCapabilities
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
              parameter:
                - name: AcceptVersions
                  allowedValues:
                    value:
                      - 2.0.0
                - name: AcceptFormats
                  allowedValues:
                    value:
                      - text/xml
            - name: DescribeFeatureType
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: ListStoredQueries
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: DescribeStoredQueries
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: GetPropertyValue
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: GetFeature
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: GetFeatureWithLock
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: Transaction
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
              constraints:
                - name: AutomaticDataLocking
                  novalues:
                  defaultvalue: TRUE
                - name: PreservesSiblingOrder
                  novalues:
                  defaultvalue: TRUE
            - name: LockFeature
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: CreateStoredQuery
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
            - name: DropStoredQuery
              dcp:
                http:
                  get:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
                  post:
                    type: simple
                    href: "{{.Onlineresourceurl}}{{.Path}}?"
          constraint:
            - name: ImplementsBasicWFS
              noValue:
              defaultValue: TRUE
            - name: ImplementsTransactionalWFS
              noValue:
              defaultValue: FALSE
            - name: ImplementsLockingWFS
              noValue:
              defaultValue: FALSE
            - name: KVPEncoding
              noValue:
              defaultValue: TRUE
            - name: XMLEncoding
              noValue:
              defaultValue: TRUE
            - name: SOAPEncoding
              noValue:
              defaultValue: FALSE
            - name: ImplementsInheritance
              noValue:
              defaultValue: FALSE
            - name: ImplementsRemoteResolve
              noValue:
              defaultValue: FALSE
            - name: ImplementsResultPaging
              noValue:
              defaultValue: TRUE
            - name: ImplementsStandardJoins
              noValue:
              defaultValue: FALSE
            - name: ImplementsSpatialJoins
              noValue:
              defaultValue: FALSE
            - name: ImplementsTemporalJoins
              noValue:
              defaultValue: FALSE
            - name: ImplementsFeatureVersioning
              noValue:
              defaultValue: FALSE
            - name: ManageStoredQueries
              noValue:
              defaultValue: FALSE
            - name: PagingIsTransactionSafe
              noValue:
              defaultValue: FALSE
            - name: CountDefault
              noValue:
              defaultValue: "1000"
            - name: QueryExpressions
              allowedValues:
                value:
                  - wfs:Query
                  - wfs:StoredQuery
        featureTypeList:
          featureType:
            - name: "{{.Prefix}}:Wood"
              title: The Great Northern Forest
              abstract: Describes the arborial diversity of the Great Northern Forest.
              keywords:
                - keyword:
                    - forest
                    - north
                    - woods
                    - arborial
                    - diversity
              metadataUrl:
                href: http://www.ogccatservice.example.com/csw.cgi?service=CSW&amp;version=2.0.2&amp;request=GetRecords&amp;constraintlanguage=CQL&amp;recordid=urn:uuid:4ee8b2d3-9409-4a1d-b26b-6782e4fa3d59
              defaultCrs: urn:ogc:def:crs:EPSG::6269
              otherCrs:
                - urn:ogc:def:crs:EPSG::32615
                - urn:ogc:def:crs:EPSG::32616
                - urn:ogc:def:crs:EPSG::32617
                - urn:ogc:def:crs:EPSG::32618
              outputFormats:
                format:
                  - application/gml+xml; version=3.2
                  - text/xml; subtype=gml/3.2.1
                  - text/xml; subtype=gml/3.1.1
                  - application/json; subtype=geojson
                  - application/json
              wgs84BoundingBox:
                lowerCorner: "-180 -90"
                upperCorner: "180 90"
            - name: "{{.Prefix}}:Lakes"
              title: The Great Northern Lakes
              abstract: Lake boundaries for all lakes in the
               Great Northern Forest.
              keywords:
                - keyword:
                    - lakes
                    - boundaries
                    - water
                    - hydro
              metadataUrl:
                href: http://www.ogccatservice.example.com/csw.cgi?service=CSW&amp;version=2.0.2&amp;request=GetRecords&amp;constraintlanguage=CQL&amp;recordid=urn:uuid:57973502-29cb-4114-8d64-9939627a0414
              defaultCrs: urn:ogc:def:crs:EPSG::6269
              otherCrs:
                - urn:ogc:def:crs:EPSG::32615
                - urn:ogc:def:crs:EPSG::32616
                - urn:ogc:def:crs:EPSG::32617
                - urn:ogc:def:crs:EPSG::32618
              outputFormats:
                format:
                  - application/gml+xml; version=3.2
                  - text/xml; subtype=gml/3.2.1
                  - text/xml; subtype=gml/3.1.1
                  - application/json; subtype=geojson
                  - application/json
              wgs84BoundingBox:
                lowerCorner: "-180 -90"
                upperCorner: "180 90"
        filterCapabilities:
          conformance:
            constraint:
              - name: ImplementsQuery
                defaultValue: "TRUE"
              - name: ImplementsAdHocQuery
                defaultValue: "TRUE"
              - name: ImplementsFunctions
                defaultValue: "TRUE"
              - name: ImplementsResourceId
                defaultValue: "TRUE"
              - name: ImplementsMinStandardFilter
                defaultValue: "TRUE"
              - name: ImplementsStandardFilter
                defaultValue: "TRUE"
              - name: ImplementsMinSpatialFilter
                defaultValue: "TRUE"
              - name: ImplementsSpatialFilter
                defaultValue: "TRUE"
              - name: ImplementsMinTemporalFilter
                defaultValue: "TRUE"
              - name: ImplementsTemporalFilter
                defaultValue: "TRUE"
              - name: ImplementsVersionNav
                defaultValue: "FALSE"
              - name: ImplementsSorting
                defaultValue: "FALSE"
              - name: ImplementsExtendedOperators
                defaultValue: "FALSE"
          scalarCapabilities:
            logicalOperators:
            comparisonOperators:
              comparisonOperator:
                - name: PropertyIsEqualTo
                - name: PropertyIsNotEqualTo
                - name: PropertyIsLessThan
                - name: PropertyIsGreaterThan
                - name: PropertyIsLessThanOrEqualTo
                - name: PropertyIsGreaterThanOrEqualTo
                - name: PropertyIsLike
                - name: PropertyIsBetween
                - name: PropertyIsNull
                - name: PropertyIsNil
          spatialCapabilities:
            geometryOperands:
              geometryOperand:
                - name: gml:Point
                - name: gml:MultiPoint
                - name: gml:LineString
                - name: gml:MultiLineString
                - name: gml:Curve
                - name: gml:MultiCurve
                - name: gml:Polygon
                - name: gml:MultiPolygon
                - name: gml:Surface
                - name: gml:MultiSurface
                - name: gml:MultiGeometry
                - name: gml:Box
                - name: gml:Envelope
