global:
  prefix: prefix
  namespace: http://namespace.geonovum.nl
  onlineResourceUrl: http://hostname
  path: /path
services:
  wms130:
    filename: ./output/wms_capabilities_1_3_0_inspire.xml
    definition:
      service:
        title: Acme Corp. Map Server
        abstract: "Map Server maintained by Acme Corporation.  Contact: webmaster@wmt.acme.com.  High-quality maps showing roadrunner nests and possible ambush locations."
        keywordList:
          keyword:
            - bird
            - roadrunner
            - ambush
        onlineResource:
          xlink: http://www.w3.org/1999/xlink
          href: "{{.Onlineresourceurl}}/"
        fees: none
        accessConstraints: none
        contactInformation:
          contactPersonPrimary:
            contactPerson: Jeff Smith
            contactOrganization: NASA
          contactPosition: Computer Scientist
          contactAddress:
            addressType: postal
            address: NASA Goddard Space Flight Center
            city: Greenbelt
            stateOrProvince: MD
            postalCode: 20771
            country: USA
          contactVoiceTelephone: +1 301 555-1212
          contactElectronicMailAddress: user@host.com
        layerLimit: 16
        maxWidth: 2048
        maxHeight: 2048

      capability:
        wmsCapabilities:
          extendedCapabilities:
            metadataUrl:
              url: https://host/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementsetname=full&id=bb652948-517e-4a61-8b7a-db61959da497
              mediaType: application/vnd.ogc.csw.GetRecordByIdResponse_xml
            supportedLanguages:
              defaultLanguage:
                language: dut
            responseLanguage:
              language: dut
          layer:
            - title: Acme Corp. Map Server
              abstract:
              crs:
                - "CRS:84"
              authorityUrl:
                name: "DIF_ID"
                onlineResource:
                  href: "http://gcmd.gsfc.nasa.gov/difguide/whatisadif.html"
              layer:
                - queryable: 0
                  title: Roads and River
                  name: ROADS_RIVERS
                  crs:
                    - "EPSG:26986"
                  attribution:
                    title: State College University
                    onlineResource:
                      xlink: http://www.w3.org/1999/xlink
                      type: simple
                      href: "http://www.university.edu/"
                    logoUrl:
                      format: image/gif
                      onlineResource:
                        xlink: http://www.w3.org/1999/xlink
                        type: simple
                        href: "http://www.university.edu/icons/logo.gif"
                  identifier:
                    authority: DIF_ID
                    value: 123456
                  featureListUrl:
                    format: XML
                    onlineResource:
                      xlink: http://www.w3.org/1999/xlink
                      type: simple
                      href: "http://www.university.edu/data/roads_rivers.gml"
                  style:
                    - name: USGS
                      title: USGS Topo Map Style
                      abstract: Features are shown in a style like that used in USGS topographic maps.
                      legendUrl:
                        width: 72
                        height: 72
                        format: image/gif
                        onlineResource:
                          xlink: http://www.w3.org/1999/xlink
                          type: simple
                          href: "http://www.university.edu/legends/usgs.gif"
                      styleSheetUrl:
                        format: text/xsl
                        onlineResource:
                          xlink: http://www.w3.org/1999/xlink
                          type: simple
                          href: "http://www.university.edu/stylesheets/usgs.xsl"
                - queryable: 1
                  title: Roads at 1:1M scale
                  name: ROADS_1MM
                  abstract: Roads at a scale of 1 to 1 million.
                  keywordList:
                    keyword:
                      - road
                      - transportation
                      - atlas
                  crs:
                    - "EPSG:26986"
                  identifier:
                    authority: DIF_ID
                    value: 123456
                  metadataUrl:
                    - type: "FGDC:1998"
                      format: text/plain
                      onlineResource:
                        xlink: http://www.w3.org/1999/xlink
                        type: simple
                        href: "http://www.university.edu/metadata/roads.txt"
                    - type: ISO19115:2003
                      format: text/xml
                      onlineResource:
                        xlink: http://www.w3.org/1999/xlink
                        type: simple
                        href: "http://www.university.edu/metadata/roads.xml"
                  style:
                    - name: ATLAS
                      title: Road atlas style
                      abstract: Roads are shown in a style like that used in a commercial road atlas.
                      legendUrl:
                        width: 72
                        height: 72
                        format: image/gif
                        onlineResource:
                          xlink: http://www.w3.org/1999/xlink
                          type: simple
                          href: "http://www.university.edu/legends/atlas.gif"
                - queryable: 1
                  title: Weather Forecast Data
                  crs:
                    - "CRS:84"
                  dimension:
                    - name: time
                      units: ISO8601
                      default: "2000-08-22"
                      value: 1999-01-01/2000-08-22/P1D
                  layer:
                    - name: Clouds
                      title: Forecast cloud cover
                      crs:
                        - "CRS:84"
                    - name: Temperature
                      title: Forecast temperature
                      crs:
                        - "CRS:84"
                    - name: Pressure
                      title: Forecast barometric pressure
                      crs:
                        - "CRS:84"
                      dimension:
                        - name: elevation
                          units: EPSG:5030
                        - name: time
                          units: ISO8601
                          default: "2000-08-22"
                          value: 1999-01-01/2000-08-22/P1D
                        - name: elevation
                          units: CRS:88
                          default: "0"
                          nearestValue: "1"
                          value: 0,1000,3000,5000,10000
                - opaque: 1
                  name: ozone_image
                  title: Global ozone distribution (1992)
                  crs:
                    - "CRS:84"
                  dimension:
                    - name: time
                      units: ISO8601
                      default: "1992"
                      value: 1992
                - name: population
                  title: World population, annual
                  crs:
                    - "CRS:84"
                  dimension:
                    - name: time
                      units: ISO8601
                      default: "2000"
                      value: 1990/2000/P1Y
