global:
  organization:    
    name: PDOK
    individual: KlantContactCenter PDOK
    position: pointOfContact
    city: Apeldoorn
    country: Nederland
    e-mail: BeheerPDOK@kadaster.nl
  boundingbox: [3.206235952734, 50.73360700723, 7.2452582753351, 53.582978813718]  
  title: kadastralegrens
  abstract: Een Kadastrale Grens is de weergave van een grens op de kadastrale kaart die door de dienst van
    het Kadaster tussen percelen vastgesteld wordt, op basis van inlichtingen van belanghebbenden en met
    gebruikmaking van de aan de kadastrale kaart ten grondslag liggende bescheiden die in elk geval de
    landmeetkundige gegevens bevatten van hetgeen op die kaart wordt weergegeven.  
  path: /kadastralekaart

service:
  wfs:
  - crs:
      default: urn:ogc:def:crs:EPSG::28992
      other:
        - urn:ogc:def:crs:EPSG::25831
        - urn:ogc:def:crs:EPSG::25832    
        - urn:ogc:def:crs:EPSG::3034    
        - urn:ogc:def:crs:EPSG::3035
        - urn:ogc:def:crs:EPSG::3038
        - urn:ogc:def:crs:EPSG::5709
        - urn:ogc:def:crs:EPSG::3857
        - urn:ogc:def:crs:EPSG::4258
        - urn:ogc:def:crs:EPSG::4326    
    version: "1.1.0"
    outputformat:
      - name: gml3
        mime_type: application/gml+xml; version=3.2
      - name: geojson
        mime_type: application/json; subtype=geojson    
      - name: json
        mime_type: application/json        
    features:
      - name: kadastralekaart:kadastralegrens
        title: kadastralegrens
        abstract: Een Kadastrale Grens is de weergave van een grens op de kadastrale kaart die door de dienst van
          het Kadaster tussen percelen vastgesteld wordt, op basis van inlichtingen van belanghebbenden en met
          gebruikmaking van de aan de kadastrale kaart ten grondslag liggende bescheiden die in elk geval de
          landmeetkundige gegevens bevatten van hetgeen op die kaart wordt weergegeven.
        boundingbox: [3.206235952734, 50.73360700723, 7.2452582753351, 53.582978813718]
        keywords:
          - Kadastrale percelen
          - infoFeatureAccessService

  - version: "2.0.0"
    outputformat:
      - name: gml3
        mime_type: application/gml+xml; version=3.2
      - name: geojson
        mime_type: application/json; subtype=geojson
      - name: json
        mime_type: application/json
    features:
      - name: kadastralekaart:kadastralegrens
        title: kadastralegrens
        abstract: Een Kadastrale Grens is de weergave van een grens op de kadastrale kaart die door de dienst van
          het Kadaster tussen percelen vastgesteld wordt, op basis van inlichtingen van belanghebbenden en met
          gebruikmaking van de aan de kadastrale kaart ten grondslag liggende bescheiden die in elk geval de
          landmeetkundige gegevens bevatten van hetgeen op die kaart wordt weergegeven.
        keywords:
          - Kadastrale percelen
          - infoFeatureAccessService          
  wms:
  - srs:
    - crs: "EPSG:28992"
      minx: -25000
      miny: 250000
      maxx: 280000
      maxy: 860000
    - crs: "EPSG:25831"
      minx: 470271
      miny: 5.56231e+06
      maxx: 795163
      maxy: 6.18197e+06
    - crs: "EPSG:25832"
      minx: 62461.6
      miny: 5.56555e+06
      maxx: 397827
      maxy: 6.19042e+06
    - crs: "EPSG:3034"
      minx: 2.61336e+06
      miny: 3.509e+06
      maxx: 3.22007e+06
      maxy: 3.84003e+06        
    - crs: "EPSG:3035"
      minx: 3.01676e+06
      miny: 3.81264e+06
      maxx: 3.64485e+06
      maxy: 4.15586e+06
    - crs: "EPSG:3857"
      minx: 281318
      miny: 6.48322e+06
      maxx: 820873
      maxy: 7.50311e+06      
    - crs: "EPSG:4258"
      minx: 50.2129
      miny: 2.52713
      maxx: 55.7212
      maxy: 7.37403
    - crs: "EPSG:4326"
      minx: 50.2129
      miny: 2.52713
      maxx: 55.7212
      maxy: 7.37403        
    - crs: "CRS:84"
      minx: 2.52713
      miny: 50.2129
      maxx: 7.37403
      maxy: 55.7212   
    version: "1.3.0"
    outputformat:
      - name: png
        mime_type: image/png
      - name: jpeg
        mime_type: image/jpeg
      - name: svg
        mime_type: image/svg+xml         
    layers:   
      - name: 'Perceel'
        title: 'Perceel'
        abstract: Overzicht van de ligging van de kadastrale percelen in Nederland. Fungeert als schakel tussen terrein
          en registratie, vervult voor externe gebruiker vaak een referentiefunctie, een ondergrond ten opzichte waarvan
          de gebruiker eigen informatie kan vastleggen en presenteren.
        keywords:
          - Kadastrale percelen
          - infoMapAccessService
        styles:
          - name: 'titlekadastralekaart:perceel_print'
            title: Visualisatie van het perceel ten behoeve van afdrukken op 180 dpi
          - name: kadastralekaart:perceel
            title: Visualisatie van het perceel
        layers:
          - name: 'KadastraleGrens'
            title: 'KadastraleGrens'
            abstract: Een Kadastrale Grens is de weergave van een grens op de kadastrale kaart die door de dienst van het
              Kadaster tussen percelen vastgesteld wordt, op basis van inlichtingen van belanghebbenden en met gebruikmaking
              van de aan de kadastrale kaart ten grondslag liggende bescheiden die in elk geval de landmeetkundige gegevens
              bevatten van hetgeen op die kaart wordt weergegeven.
            keywords:
              - Kadastrale percelen
              - infoMapAccessService
            styles:
              - name: 'kadastralekaart:kadastralegrens_print'
                title: Visualisatie van de grens op basis van type (definitief, voorlopig of administratief) ten behoeve van afdrukken op 180 dpi
              - name: kadastralekaart:kadastralegrens
                title: Visualisatie van de grens op basis van type (definitief, voorlopig of administratief
        
          - name: 'Bebouwing'
            title: 'Bebouwing'
            abstract: De laag Bebouwing is een selectie op panden van de BGT met een bgt-status “bestaand” die een huisnummer hebben.
              bevatten van hetgeen op die kaart wordt weergegeven.
            keywords:
              - bebouwing
              - infoMapAccessService
            styles:
              - name: 'kadastralekaart:bebouwing'
                title: Visualisatie van de bebouwing
              - name: kadastralekaart:kadastralegrens
                title: Visualisatie van de grens op basis van type (definitief, voorlopig of administratief
        
          - name: 'OpenbareRuimteNaam'
            title: 'OpenbareRuimteNaam'
            abstract: De laag Openbareruimtenaam  is een selectie op de openbare ruimte labels van de BGT met een bgt-status
              “bestaand” die een classificatie (openbareruimtetype) Weg en Water hebben.
            keywords:
              - openbareruimtenaam
              - infoMapAccessService
            styles:
              - name: kadastralekaart:openbareruimtenaam_print
                title: Visualisatie van openbareruimtenaam ten behoeve van afdrukken op 180 dpi
              - name: kadastralekaart:openbareruimtenaam
                title: Visualisatie van de openbareruimtenaam        
  # - wmts:
  #     version: "1.0.0"
  #     layers:
  #       - name: 'kadastralekaart'
  #         title: 'kadastralekaart'
  #         abstract: Overzicht van de ligging van de kadastrale percelen in Nederland. Fungeert als schakel tussen terrein en registratie, vervult voor externe gebruiker vaak een referentiefunctie, een ondergrond ten opzichte waarvan de gebruiker eigen informatie kan vastleggen en presenteren.
  #         keywords:
  #           - Kadastrale percelen
  #           - Kadaster
  #         # styles:
  #         #   - name: 'default'
  #         #     title: Visualisatie KadastraleKaart  
