organization: PDOK
identification: kadastralekaart
dataset: kadastralekaart
inspire: true
urlwms: https://geodata.nationaalgeoregister.nl/kadastralekaart/wms/v4_0
urlwfs: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0
urlwmts: https://geodata.nationaalgeoregister.nl/kadastralekaart/wmts/v4_0
boundingbox: WGS84
metadata-resource-id: 97cf6a64-9cfc-4ce6-9741-2db44fd27fca
features:
  - name: kadastralekaartv4:kadastralegrens
    title: kadastralegrens
    abstract: Een Kadastrale Grens is de weergave van een grens op de kadastrale kaart die door de dienst van
      het Kadaster tussen percelen vastgesteld wordt, op basis van inlichtingen van belanghebbenden en met
      gebruikmaking van de aan de kadastrale kaart ten grondslag liggende bescheiden die in elk geval de
      landmeetkundige gegevens bevatten van hetgeen op die kaart wordt weergegeven.
    keywords:
      - Kadastrale percelen
      - infoMapAccessService
    bounding-box: WGS84
    crs:
      - 'EPSG:28992'
      - 'EPSG:3035'
      - 'EPSG:3038'

layers:
  name: 'kadastralekaart'
  abstract: Overzicht van de ligging van de kadastrale percelen in Nederland. Fungeert als schakel tussen terrein
  en registratie, vervult voor externe gebruiker vaak een referentiefunctie, een ondergrond ten opzichte waarvan
  de gebruiker eigen informatie kan vastleggen en presenteren.
  keywords:
    - Kadastrale percelen
    - infoMapAccessService
  bounding-box: NED
  layertype: group
  crs:
    - 'EPSG:28992'
    - 'EPSG:25831'
    - 'EPSG:25832'
    - 'EPSG:3034'
    - 'EPSG:3035'
    - 'EPSG:3857'
    - 'EPSG:4258'
    - 'EPSG:4326'
    - 'CRS:84'
  srs:
    - 'EPSG:28992'
    - 'EPSG:25831'
    - 'EPSG:25832'
    - 'EPSG:3034'
    - 'EPSG:3035'
    - 'EPSG:3857'
    - 'EPSG:4258'
    - 'EPSG:4326'
    - 'CRS:84'

    - name: Perceel
      title: Perceel
      abstract: Een perceel is een stuk grond waarvan het Kadaster de grenzen heeft gemeten en dat bij het Kadaster
        een eigen nummer heeft. Een perceel is een begrensd deel van het Nederlands grondgebied dat kadastraal
        geïdentificeerd is en met kadastrale grenzen begrensd is.
      keywords:
        - Kadastrale percelen
        - infoMapAccessService
      bounding-box: NED
      layertype: group
      crs:
        - 'EPSG:28992'
        - 'EPSG:25831'
        - 'EPSG:25832'
        - 'EPSG:3034'
        - 'EPSG:3035'
        - 'EPSG:3857'
        - 'EPSG:4258'
        - 'EPSG:4326'
        - 'CRS:84'
      srs:
        - 'EPSG:28992'
        - 'EPSG:25831'
        - 'EPSG:25832'
        - 'EPSG:3034'
        - 'EPSG:3035'
        - 'EPSG:3857'
        - 'EPSG:4258'
        - 'EPSG:4326'
        - 'CRS:84'

        style_name: kadastralekaartv4:perceel_print
        style_title: Visualisatie van het perceel.

      - name: Perceel
        title: Perceel
        abstract: Een perceel is een stuk grond waarvan het Kadaster de grenzen heeft gemeten en dat bij het Kadaster
          een eigen nummer heeft. Een perceel is een begrensd deel van het Nederlands grondgebied dat kadastraal
          geïdentificeerd is en met kadastrale grenzen begrensd is.
        keywords:
          - Kadastrale percelen
          - infoMapAccessService
        bounding-box: NED
        layertype: layer
        crs:
          - 'EPSG:28992'
          - 'EPSG:25831'
          - 'EPSG:25832'
          - 'EPSG:3034'
          - 'EPSG:3035'
          - 'EPSG:3857'
          - 'EPSG:4258'
          - 'EPSG:4326'
          - 'CRS:84'
        srs:
          - 'EPSG:28992'
          - 'EPSG:25831'
          - 'EPSG:25832'
          - 'EPSG:3034'
          - 'EPSG:3035'
          - 'EPSG:3857'
          - 'EPSG:4258'
          - 'EPSG:4326'
          - 'CRS:84'
        styles:
          - name: 'titlekadastralekaartv4:perceel_print'
            title: 'titlekadastralekaartv4:perceel_print'
          - name: default
            value: Visualisatie van het perceel ten behoeve van afdrukken op 180 dpi.

#    style_name: kadastralekaartv4:perceel_print
#    style_title: Visualisatie van het perceel ten behoeve van afdrukken op 180 dpi.

