serviceidentification:
    title: kadastralekaart
    abstract: Overzicht van de ligging van de kadastrale percelen in Nederland. Fungeert als schakel tussen terrein en registratie, vervult voor externe gebruiker vaak een referentiefunctie, een ondergrond ten opzichte waarvan de gebruiker eigen informatie kan vastleggen en presenteren.
    keywords:
      keyword:
      - PDOK        
      - Kadaster
      - Kadastrale percelen
    accesscontraints: http://creativecommons.org/publicdomain/zero/1.0/deed.nl