organizations:
  PDOK:
    name: PDOK
    individual: KlantContactCenter PDOK
    position: pointOfContact
    city: Apeldoorn
    country: Nederland
    e-mail: BeheerPDOK@kadaster.nl
  RWS:
    name: Beheer RWS
    individual: KlantContactCenter RWS
    position: fd
    city: Apeldoorn
    country: Nederland
    e-mail: BeheerPDOK@kadaster.nll

datasets:
  kadastralekaart:
    name: kadastralekaart
    metadata-resource-id: a29917b9-3426-4041-a11b-69bcb2256904


identification:
  kadastralekaart:
    title: KadastraleKaartv4
    abstract: Overzicht van de ligging van de kadastrale percelen in Nederland. Fungeert als schakel tussen terrein en registratie, vervult voor externe gebruiker vaak een referentiefunctie, een ondergrond ten opzichte waarvan de gebruiker eigen informatie kan vastleggen en presenteren.
    keywords:
      - Kadaster
      - kadastrale percelen

format:
  - name: gml3
    mime_type: application/gml+xml; version=3.2

boundingbox:
  WGS84:
    coordinates: [3.206235952734, 50.73360700723, 7.2452582753351, 53.582978813718]
    srs: 84
  NED:
    coordinates: [2.52713, 50.2129, 7.37403, 55.7212]
    srs: 28992

crs:
  EPSG:28992:
    value: urn:ogc:def:crs:EPSG::28992
  EPSG:3035:
    value: urn:ogc:def:crs:EPSG::3035
  EPSG:3038:
    value: urn:ogc:def:crs:EPSG::3038
  EPSG:25831:
    value: urn:ogc:def:crs:EPSG::25831
  EPSG:25832:
    value: urn:ogc:def:crs:EPSG::25832
  EPSG:3034:
    value: urn:ogc:def:crs:EPSG::3034
  EPSG:5709:
    value: urn:ogc:def:crs:EPSG::5709
  EPSG:3857:
    value: urn:ogc:def:crs:EPSG::3857
  EPSG:4258:
    value: urn:ogc:def:crs:EPSG::4258
  EPSG:4326:
    value: urn:ogc:def:crs:EPSG::4326

srs:
  EPSG:28992:
    value: CRS="EPSG:28992"
      minx="-25000" miny="250000" maxx="280000" maxy="860000"
  EPSG:25831:
    value: CRS="EPSG:25831"
      minx="470271" miny="5.56231e+06" maxx="795163" maxy="6.18197e+06"
  EPSG:25832:
    value: CRS="EPSG:25832"
      minx="62461.6" miny="5.56555e+06" maxx="397827" maxy="6.19042e+06"
  EPSG:3034:
    value: CRS="EPSG:3034"
      minx="2.61336e+06" miny="3.509e+06" maxx="3.22007e+06" maxy="3.84003e+06"
  EPSG:3035:
    value: CRS="EPSG:3035"
      minx="3.01676e+06" miny="3.81264e+06" maxx="3.64485e+06" maxy="4.15586e+06"
  EPSG:3857:
    value: CRS="EPSG:3857"
      minx="281318" miny="6.48322e+06" maxx="820873" maxy="7.50311e+06"
  EPSG:4258:
    value: CRS="EPSG:4258"
      minx="50.2129" miny="2.52713" maxx="55.7212" maxy="7.37403"
  EPSG:4326:
    value: CRS="EPSG:4326"
      minx="50.2129" miny="2.52713" maxx="55.7212" maxy="7.37403"
  CRS:84:
    value: CRS="CRS:84"
      minx="2.52713" miny="50.2129" maxx="7.37403" maxy="55.7212"