operationsmetadata:
  operation: 
    - name: GetCapabilities
      DCP:
        HTTP:
          GET:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&
          #POST: no POST for GetCapabilities
      parameter:
        - name: AcceptVersions
          allowedvalues: 
            value: 
            - 2.0.0
            - 1.1.0
            - 1.0.0
        - name: AcceptFormats
          allowedvalues: 
            value: 
            - text/xml
        - name: Sections
          allowedvalues: 
            value: 
            - ServiceIdentification
            - ServiceProvider
            - OperationsMetadata
            - FeatureTypeList
            - Filter_Capabilities
    - name: DescribeFeatureType
      DCP:
        HTTP:
          GET:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&
          # POST: no POST for DescribeFeatureType
      parameter:
        - name: outputFormat
          allowedvalues: 
            value: 
            - application/gml+xml; version=3.2
            - text/xml; subtype=gml/3.2.1
            - text/xml; subtype=gml/3.1.1
            - text/xml; subtype=gml/2.1.2
    - name: GetFeature
      DCP:
        HTTP:
          GET:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&
          POST:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&            
      parameter:
        - name: outputFormat
          allowedvalues: 
            value: 
            - application/gml+xml; version=3.2
            - text/xml; subtype=gml/3.2.1
            - text/xml; subtype=gml/3.1.1
            - text/xml; subtype=gml/2.1.2
            - application/json; subtype=geojson
            - application/json
    # - name: GetPropertyValue 
    - name: ListStoredQueries
      DCP:
        HTTP:
          GET:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&
          # POST: no POST for ListStoredQueries
    - name: DescribeStoredQueries
      DCP:
        HTTP:
          GET:
            type: simple
            href: https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?SERVICE=WFS&language=eng&
          # POST: no POST for DescribeStoredQueries


conformance:
  constraint:
  - name: ImplementsQuery
    defaultvalue: "TRUE"
  - name: ImplementsAdHocQuery
    defaultvalue: "TRUE"
  - name: ImplementsFunctions
    defaultvalue: "FALSE"
  - name: ImplementsResourceId
    defaultvalue: "TRUE"
  - name: ImplementsMinStandardFilter
    defaultvalue: "TRUE"
  - name: ImplementsStandardFilter
    defaultvalue: "TRUE"
  - name: ImplementsMinSpatialFilter
    defaultvalue: "TRUE"
  - name: ImplementsSpatialFilter
    defaultvalue: "FALSE"
  - name: ImplementsMinTemporalFilter
    defaultvalue: "TRUE"
  - name: ImplementsTemporalFilter
    defaultvalue: "FALSE"
  - name: ImplementsVersionNav
    defaultvalue: "FALSE"
  - name: ImplementsSorting
    defaultvalue: "TRUE"
  - name: ImplementsExtendedOperators
    defaultvalue: "FALSE"
  - name: ImplementsMinimumXPath
    defaultvalue: "TRUE"
  - name: ImplementsSchemaElementFunc
    defaultvalue: "FALSE"

idcapabilities:
  resourceidentifier:
    name: fes:ResourceId

scalarcapabilities:
  logicaloperators:
  comparisonoperators:
    comparisonoperator:
    - name: PropertyIsEqualTo
    - name: PropertyIsNotEqualTo
    - name: PropertyIsLessThan
    - name: PropertyIsGreaterThan
    - name: PropertyIsLessThanOrEqualTo
    - name: PropertyIsGreaterThanOrEqualTo
    - name: PropertyIsLike
    - name: PropertyIsBetween

spatialcapabilities:
  geometryoperands:
    geometryoperand:
    - name: gml:Point
    - name: gml:MultiPoint
    - name: gml:LineString
    - name: gml:MultiLineString
    - name: gml:Curve
    - name: gml:MultiCurve
    - name: gml:Polygon
    - name: gml:MultiPolygon
    - name: gml:Surface
    - name: gml:MultiSurface
    - name: gml:Box
    - name: gml:Envelope

  spatialoperators:
    spatialoperator:
    - name: Equals
    - name: Disjoint
    - name: Touches
    - name: Within
    - name: Overlaps
    - name: Crosses
    - name: Intersects
    - name: Contains
    - name: DWithin
    - name: Beyond
    - name: BBOX

# temporalcapabilities:
#   temporaloperands:
#     temporaloperand:
#   temporaloperators:
#     temporaloperator:
